name: flutter_gpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  avatar_glow: ^2.0.2
  chat_gpt_sdk: ^2.1.2
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  flutter_tts: ^3.6.3
  google_fonts: ^4.0.3
  introduction_screen: ^3.1.7
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  speech_to_text: ^6.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_icons:
  image_path: "icons/logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#343541"
  image: icons/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
